### ISSUE TITLE
Week 1: Let me in!

### ISSUE THREAD

**Issue by marcduiker** [marcduiker/intro-to-serverless-pro-max#7]
Week 1 Step 5 ⬤⬤⬤⬤⬤◯◯◯◯ | 🕐 Estimated completion: 25-35 minutes

# Let me in!

## ✅ Tasks:
- [ ] Run `git pull origin [BRANCH_NAME]`
- [ ] ***1:*** Add on to the HTTP Trigger in the previous issue to check if the user’s parameter input of “password” equals `letmein`.
    - If it does, output "Access granted."
    - If it doesn’t equal the correct password, output “Access denied.”
- [ ] 🚀 Commit the update function's code in a file named `hackervoice/index.js` to the root of the `hackervoice` branch!

> :exclamation: **Do not merge the branch!!**

## 🚧 Test your Work
When you paste your **Function URL** in your browser or make a GET request with **Postman** with a `password` parameter of "letmein", you should get a response of “Access granted.“. Otherwise, your function should output “Access denied.“.

:exclamation: Make sure you follow the *exact* responses we provided. `Access denied.` and `Access granted.`

## 1: Return from a Function

In the previous step, we received the password (the user's input). Now, we need to return either `Access denied.` or `Access granted.` to the user based on their input. **We can do this by returning it in the body of the request!**

> :bulb: Recall the `context.res` object we saw in the HTTP Trigger template.

```js
context.res = {
    // status: 200, /* Defaults to 200 */
    body: your_response
};
```

Place your message to the user in `your_response`!

**Comment by marcduiker** [comment]
[HELP]

**Comment by marcduiker** [comment]
[HELP] How do I use this help?

**Comment by marcduiker** [comment]
[HELP] The bot isn't checking my code

**Comment by marcduiker** [comment]
[HELP] Why isn't the bot responding???
